server:
  port: 8001
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ztf.api.bean
spring:
  application:
    name: mycloud-provider # eureka页面 application显示的名称。EurekaServer中服务名默认转成大写的。
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/display?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF8
    username: root
    password: P@ssw0rd
#  cloud:
#    service-registry:
#      auto-registration:
#        enabled: false # 禁止服务注册发现功能。
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port} # eureka页面status显示的内容
#    register-with-eureka: false # 禁止服务注册功能。
## 自定义的一个starter
local:
  orange:
    id: 007
    name: myorange
    age: 26

info: # eureka页面status点击跳转监控页面 显示的内容
  app.name: ${spring.application.name}
  company.name: www.orange.com
  build.artifactId: mycloud-provider
  build.version: 1.0
